plugins:
  - '@trivago/prettier-plugin-sort-imports'
  - prettier-plugin-tailwindcss
singleQuote: true
semi: true
useTabs: false
bracketSpacing: true
trailingComma: all
tailwindFunctions:
  - 'tv'
printWidth: 100
importOrder:
  - '^react$'
  - '^next'
  - '<THIRD_PARTY_MODULES>'
  - '^@/components/(.*)$'
  - '^@/hooks/(.*)$'
  - '^@/utils/(.*)$'
  - '^@/types/(.*)$'
  - '^[./]'
importOrderSeparation: true
importOrderSortSpecifiers: true
importOrderParserPlugins:
  - 'typescript'
  - 'jsx'
  - 'decorators-legacy'
