name: 🎨 UI Task
description: UI, layout, responsive...
title: "[UI]: "
labels: ["frontend", "ui", "task"]
assignees: []

body:
  - type: input
    id: goal
    attributes:
      label: "📄 Goal"
      placeholder: "Create login form according to Figma"
    validations:
      required: true

  - type: textarea
    id: checklist
    attributes:
      label: "✅ Work checklist"
      description: "Write checklist in Markdown (each line should have `- [ ]`)"
      placeholder: |
        - [ ] Checklist 1
        - [ ] Checklist 2
        - [ ] Checklist 3

  - type: textarea
    id: related
    attributes:
      label: "📌 Related"
      placeholder: "PR, Figma link, issue #..."
