name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      backend_changed: ${{ steps.paths.outputs.backend }}
      frontend_changed: ${{ steps.paths.outputs.frontend }}
    steps:
      - uses: actions/checkout@v5
      - name: Determine changed paths
        id: paths
        uses: dorny/paths-filter@v2
        with:
          filters: |
            backend:
              - 'be/**'
              - '.github/**'
            frontend:
              - 'fe/**'
              - '.github/**'

      - name: Debug paths-filter outputs
        run: |
          echo "Changed files (git diff):"
          # show changed files between base and head (works in PR contexts)
          git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1 || true
          git --no-pager diff --name-only origin/${{ github.event.pull_request.base.ref }}...HEAD || true

  backend_test:
    needs: filter
    if: ${{ github.event.pull_request.draft != true && needs.filter.outputs.backend_changed == 'true'}}
    runs-on: ubuntu-latest
    container:
      image: ruby:3.4.3
    defaults:
      run:
        working-directory: ./be
    services:
      mysql-test:
        image: mysql:8
        env:
          MYSQL_DATABASE: db-test
          MYSQL_ROOT_PASSWORD: root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install dependencies for faiss gem
        run: |
          apt-get update
          apt-get install -y libopenblas-dev libomp-dev

      - name: Bundle Install
        run: |
          bundle install

      - name: Prepare Database
        run: |
          cp config/database-ci.yml config/database.yml
          RAILS_ENV=test bundle exec rails db:drop db:create db:migrate

      - name: Run BE tests - Rubocop
        run: |
          bundle exec rubocop --require rubocop/formatter/checkstyle_formatter --format RuboCop::Formatter::CheckstyleFormatter --no-color app/ lib/

      - name: Run BE tests - RSpec
        run: |
          bundle exec rspec --format documentation

  frontend_test:
    needs: filter
    if: ${{ github.event.pull_request.draft != true && needs.filter.outputs.frontend_changed == 'true'}}
    runs-on: ubuntu-latest
    container:
      image: node:22
    defaults:
      run:
        working-directory: ./fe

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Mark workspace safe for git (fix dubious ownership)
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Install dependencies
        run: |
          npm ci

      - name: Run FE tests
        run: |
          npm run lint -- --debug

      - name: Build app
        run: |
          npm run build
